# Generated by Django 4.2.1 on 2023-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('linea', models.CharField(blank=True, max_length=50)),
                ('sublinea', models.CharField(blank=True, max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('precio1', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ptje1', models.IntegerField(blank=True)),
                ('ptjeReal', models.IntegerField(blank=True)),
                ('precioCalculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('maximo', models.IntegerField(blank=True)),
                ('minimo', models.IntegerField(blank=True)),
                ('estatus', models.IntegerField(blank=True)),
                ('nombreStatus', models.CharField(blank=True, max_length=50)),
                ('tipoProd', models.IntegerField(blank=True)),
                ('tipoProdDesc', models.CharField(blank=True, max_length=50)),
                ('codigosAlternos', models.CharField(blank=True, max_length=100)),
                ('activo', models.CharField(blank=True, max_length=10)),
                ('prov', models.IntegerField(blank=True)),
                ('nombreProveedor', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('codigoSat', models.CharField(blank=True, max_length=50)),
                ('nomCodSat', models.CharField(blank=True, max_length=100)),
                ('unidadSat', models.CharField(blank=True, max_length=50)),
                ('nomUniSat', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo', 'nombre'],
                'indexes': [models.Index(fields=['codigo', 'nombre'], name='product_pro_codigo_d3b5b4_idx')],
            },
        ),
    ]
