# Generated by Django 4.2.1 on 2024-01-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_producto_codigosalternos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='prov',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
