# Generated by Django 4.2.1 on 2024-03-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producto_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
