# Generated by Django 4.2.1 on 2024-05-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_producto_existencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='onlinePrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
